# helpful directories
export core="/Users/kevin/cleversafe/core_workspaces/"
export cleverkit="/Users/kevin/cleversafe/cleverkit"

# auto-gen at end
export dsnet_num=543 # generated by set_dsnet.sh
export vm_dc5428r_ss_01=10.137.10.11 # generated by set_dsnet.sh
export slicestor_10_11=10.137.10.11 # generated by set_dsnet.sh
export vm_dc5428r_ss_02=10.137.10.12 # generated by set_dsnet.sh
export slicestor_10_12=10.137.10.12 # generated by set_dsnet.sh
export vm_dc5428r_ss_03=10.137.10.13 # generated by set_dsnet.sh
export slicestor_10_13=10.137.10.13 # generated by set_dsnet.sh
export vm_dc5428r_ss_04=10.137.10.14 # generated by set_dsnet.sh
export slicestor_10_14=10.137.10.14 # generated by set_dsnet.sh
export vm_dc5428r_ss_05=10.137.10.15 # generated by set_dsnet.sh
export slicestor_10_15=10.137.10.15 # generated by set_dsnet.sh
export vm_dc5428r_acc_01=10.137.10.17 # generated by set_dsnet.sh
export accesser_10_17=10.137.10.17 # generated by set_dsnet.sh
export vm_dc5428r_acc_02=10.137.10.18 # generated by set_dsnet.sh
export accesser_10_18=10.137.10.18 # generated by set_dsnet.sh
export vm_dc5428r_mgr_01=10.137.10.16 # generated by set_dsnet.sh
export manager_10_16=10.137.10.16 # generated by set_dsnet.sh
export vm_dc5428r_init_01=10.137.10.10 # generated by set_dsnet.sh
export initiator_10_10=10.137.10.10 # generated by set_dsnet.sh
